// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC66-7QUiM81qSoENLDxJqJ-ZkC5mwvafw',
    appId: '1:868943858988:web:f5ed2c1dc3fb993f797089',
    messagingSenderId: '868943858988',
    projectId: 'spotify-clone-f8316',
    authDomain: 'spotify-clone-f8316.firebaseapp.com',
    storageBucket: 'spotify-clone-f8316.appspot.com',
    measurementId: 'G-BB0ZXJ4N3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHfhopPsnOSUNZG-umLarLmMvTauX43hE',
    appId: '1:868943858988:android:a946ea371a0c25f0797089',
    messagingSenderId: '868943858988',
    projectId: 'spotify-clone-f8316',
    storageBucket: 'spotify-clone-f8316.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAD1u6TQA_1mpV4mxps6ui56XYERW7u024',
    appId: '1:868943858988:ios:9de8a69b13ab565c797089',
    messagingSenderId: '868943858988',
    projectId: 'spotify-clone-f8316',
    storageBucket: 'spotify-clone-f8316.appspot.com',
    iosBundleId: 'com.example.spotifyDummy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAD1u6TQA_1mpV4mxps6ui56XYERW7u024',
    appId: '1:868943858988:ios:9de8a69b13ab565c797089',
    messagingSenderId: '868943858988',
    projectId: 'spotify-clone-f8316',
    storageBucket: 'spotify-clone-f8316.appspot.com',
    iosBundleId: 'com.example.spotifyDummy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC66-7QUiM81qSoENLDxJqJ-ZkC5mwvafw',
    appId: '1:868943858988:web:0691cef391514177797089',
    messagingSenderId: '868943858988',
    projectId: 'spotify-clone-f8316',
    authDomain: 'spotify-clone-f8316.firebaseapp.com',
    storageBucket: 'spotify-clone-f8316.appspot.com',
    measurementId: 'G-KDJQ96S4KX',
  );
}
